### ISSUE TITLE
Checklist loads forever and causes drop in performant

### ISSUE THREAD

**Issue by shaggyfeng** [delashum/obsidian-checklist-plugin#109] opened 2022-01-02 21:04 UTC
![Screenshot (270)](https://user-images.githubusercontent.com/75353922/147889394-22c0183f-6e90-4b14-82cb-3d96b8481b43.png)

**Comment by shaggyfeng** [comment] 2022-01-02 21:07
V 2.0.1
It works yesterday, before and after the new update. However, once I relaunch Obsidian.exe, the problem occurs.

**Comment by MikhaD** [comment] 2022-01-05 13:26
I am having the same issue with v2.0.1

**Comment by mkNucleus** [comment] 2022-01-05 15:33
I have the same problem with 2.0.1. Thanks

**Comment by yujiapingyu** [comment] 2022-01-07 17:12
I am having the same issue with v2.0.1
The load state will remain after the restart. Thanks!

**Comment by shaggyfeng** [comment] 2022-01-09 19:40
Tried `2.0.2`, the problem remains

**Comment by delashum** [comment] 2022-01-09 22:00
yeah `2.0.2` solved a different problem. I'm still not sure on this one as I haven't been able to reproduce. I have a couple ideas:
1. All you who are having issues, what is your value in the `Include Files` setting. The contract for that changed in v2 and I'm wondering if you need to update the value in there?
2. Is anyone seeing this in your vault on your computer? How about on your computer if you enable the `emulateMobile` flag? (you can do that by opening the console and typing `app.emulateMobile(true)`. If you can repro on your machine are there any logs?

**Comment by shaggyfeng** [comment] 2022-01-09 22:44
> 

1. My value in the `Include Files` setting is empty.
2. I tried the mobile mode on PC. With the Mobile mode on, `2.0.2` works, no issue. In desktop mode, the bug remains.

**Comment by shaggyfeng** [comment] 2022-01-09 22:48
> yeah `2.0.2` solved a different problem. I'm still not sure on this one as I haven't been able to reproduce. I have a couple ideas:
> 
> 1. All you who are having issues, what is your value in the `Include Files` setting. The contract for that changed in v2 and I'm wondering if you need to update the value in there?
> 2. Is anyone seeing this in your vault on your computer? How about on your computer if you enable the `emulateMobile` flag? (you can do that by opening the console and typing `app.emulateMobile(true)`. If you can repro on your machine are there any logs?

1. My value in the Include Files setting is empty.
2. I tried the mobile mode on PC. With the Mobile mode on, 2.0.2 works, no issue. In desktop mode, the bug remains.

**Comment by shaggyfeng** [comment] 2022-01-09 23:08
How to get any log for this bug, though?

**Comment by spencewenski** [comment] 2022-01-21 02:49
I'm seeing this on both Mac and Linux with 2.0.2. It appears to stay in the loading state (with the spinning loading animation) until a change occurs that triggers a re-render, such as creating a new file.

**Comment by spencewenski** [comment] 2022-01-21 03:00
This is probably a duplicate of #80

**Comment by MATCHaB1** [comment] 2022-01-22 14:20
The current version is 2.0.2 and I have encountered the same situation where the plug-in is always loaded indefinitely every time I reopen it

**Comment by jonnyberanek** [comment] 2022-01-28 15:20
On Windows, I am getting this problem on any current 2.x version. Downgrading to 1.2.3 seems to work fine for me.

**Comment by shaggyfeng** [comment] 2022-01-30 00:15
> On Windows, I am getting this problem on any current 2.x version. Downgrading to 1.2.3 seems to work fine for me.

Yes, I did the same thing.

**Comment by gmaciocci** [comment] 2022-02-03 11:02
Same thing here on windows 11, plugin version 2.02

**Comment by alex-kovac** [comment] 2022-02-10 21:33
@gmaciocci is right, it seems that as soon as one adds a query in a note e.g. :

```query
tag:#todo
```

Checklist renders quickly. This is on Mac M1.

**Comment by shaggyfeng** [comment] 2022-02-27 17:07
> I'm seeing this on both Mac and Linux with 2.0.2. It appears to stay in the loading state (with the spinning loading animation) until a change occurs that triggers a re-render, such as creating a new file. Once I create a file, the plugin loads immediately and functions as expected.

This seems to be a potential solution. I wish I could code with Typescript. For now, the 1.X version works just fine.

**Closed** 2022-07-04 13:40 UTC
