### ISSUE TITLE
Frequent "hangs" when typing, and 100% CPU on the electron web-rendering thread.

### ISSUE THREAD

**Issue by jeffvogelsang** [delashum/obsidian-checklist-plugin#81] opened 2021-08-15 16:24 UTC
When I enable the checklist plugin I get "hangs" when typing, and 100+% CPU on the electron web-rendering thread. Basically after about a sentence's worth of typing, the editor hangs, and buffers keystrokes, which show up a second or two later. De-activating the checklist plugin resolves the issue. Also, while indexing about 1500 items a vault, if the plugin is enabled, it takes 40ish minutes. With Checklist deactivated, the indexing takes 5 seconds. I'm not sure how to troubleshoot this further.

**Comment by jeffvogelsang** [comment] 2021-08-15 17:04
Actually, a bit of info. I had removed the todo tag to scan all files in the vault. Adding back a tag speeds things up a bit. So there may be something about how the code is scanning the vault for all the '- [ ] ' strings that is causing the slowdown.

**Comment by delashum** [comment] 2021-08-16 22:26
Duplicate of #70

**Closed by delashum** 2021-08-16 22:26 UTC
