### ISSUE TITLE
The format of the todo list in IOS is messy

### ISSUE THREAD

**Issue by Dolores-Z** [delashum/obsidian-checklist-plugin#84] opened 2021-08-22 15:59 UTC
![647B678B-F2D4-4B3A-8112-6D256AA33930](https://user-images.githubusercontent.com/89349762/130361783-e8338d63-73b5-41c3-96bb-f8ea870fb73c.jpeg)

**Comment by mrkteq** [comment] 2021-08-22 16:01
+1

**Comment by tristancade** [comment] 2021-09-29 13:37
+1

**Comment by delashum** [comment] 2021-10-05 15:07
This is technically a duplicate of #78, thanks for adding the screenshot to illustrate the issue

**Closed by delashum** 2021-10-05 15:07 UTC
