### ISSUE TITLE
Plugin leading to slow down obsidian

### ISSUE THREAD

**Issue by nihitkhandelwal-eng** [delashum/obsidian-checklist-plugin#107] opened 2021-12-22 13:15 UTC
I was experiencing slow obsidian to almost crash obsidian for a few days & I narrowed it down to the checklist plugin.
It does not happen always though, so if the tag field to look for is left empty, it will cause obsidian to slow down but not if there is some tag present.

**Comment by delashum** [comment] 2021-12-26 22:30
This is a duplicate of #97 working on it this week!

**Closed by delashum** 2021-12-26 22:30 UTC
