### ISSUE TITLE
[Feature Request] Option for Multiple Tags

### ISSUE THREAD

**Issue by jphaupt** [delashum/obsidian-checklist-plugin#100] opened 2021-11-24 13:01 UTC
I guess this should be an option as not everyone would want it, but it would be nice to be able to have a checklist item have multiple labels. For example: 

```
#todo/topic
- [ ] something
- [ ] another thing
- [ ] something urgent #todo/today
- [ ] another thing 
```

Then I want all four of these to show up in `#todo/topic`, but only the third one to show up in the other checklist `#todo/today`. Then if I tick that one it would be removed from both lists. At the moment, it only shows up in `#todo/topic`.

**Comment by delashum** [comment] 2021-12-26 20:49
duplicate of #44

**Closed by delashum** 2021-12-26 20:49 UTC

**Comment by jphaupt** [comment] 2021-12-26 21:08
Woops, thanks!

**Comment by delashum** [comment] 2021-12-26 21:09
no worries :) it's a good suggestion. Almost done with the implementation, it'll be in the next release here in a few days
