### ISSUE TITLE
Multi Tag Grouping

### ISSUE THREAD

**Issue by chetachiezikeuzor** [delashum/obsidian-checklist-plugin#54] opened 2021-05-13 17:56 UTC
First, I'd like to say that I really love this plugin! Excellent work on both design and functionality. I wanted to propose a feature request:

1. Ability for Checklist to catch todos from multiple tags (similar to page grouping).
2. Ability for Checklist to filter out which tags to be displayed/ignored.

Thanks so much, stay safe!

<img width="307" alt="Screen Shot 2021-05-13 at 12 51 10 PM" src="https://user-images.githubusercontent.com/79069364/118165440-e7a47a00-b3e9-11eb-8620-59c891946cb6.png">

**Comment by delashum** [comment] 2021-05-22 22:59
Thanks! Also, good suggestion. This is an idea i've been toying with and will probably implement soon, will keep this issue updated

**Comment by pwolfert** [comment] 2021-11-04 00:40
I'd also find this feature useful. It looks like there is existing functionality to group by tag, but it only applies when the `Tag name` option is left blank, right? Could the feature request be fulfilled by adding the ability to capture multiple named tags? As an example, if the plugin allowed me to specify the two tags `#todo-now` and `#todo-later`, and I set `Group By` to `Tag`, would I get two sections under my checklist panel?

**Comment by delashum** [comment] 2021-12-26 22:22
Grouping will also group by sub tags (i.e. #todo/a #todo/b), adding support for multiple tags soon

**Comment by delashum** [comment] 2021-12-26 22:24
Also this is a duplicate of both #44 and #49. Fix coming soon for both!

**Closed by delashum** 2021-12-26 22:24 UTC
Labels: enhancement
