### ISSUE TITLE
plugin can't be loaded on mobile app (iOS)

### ISSUE THREAD

**Issue by netlynker** [delashum/obsidian-checklist-plugin#75] opened 2021-08-03 23:08 UTC
Hi,

Plugin can't be loaded on mobile editor on iOS with the message "Failed to load obsidian-checklist-plugin". In setting it is disabled. Enabling it fails with same error message. 

Regards,

**Comment by cstromblad** [comment] 2021-08-04 20:38
(For me Android and ChromeOS)

**Comment by mochsner** [comment] 2021-08-12 03:25
Isn't this a duplicate of #63 ?

**Comment by delashum** [comment] 2021-08-13 02:09
yep, see #63 for updates

**Closed by delashum** 2021-08-13 02:09 UTC
