### ISSUE TITLE
plugin loads forever and then crashes Obsidian

### ISSUE THREAD

**Issue by smile4yourself** [delashum/obsidian-checklist-plugin#126] opened 2022-03-06 18:40 UTC
The problem is I do not know how to setup the configuration to only read *.md files in my vault. I have unprocessed OCR files in my vault as well as pdf and other files. using your cryptic programming language ;-) would you please post what to write in order to read only xxxx.md files. 

I think that other people have problems with the plugin for the same reason. I tried the plugin in a small text-only vault, and it worked there, but my large vault with both text and unprocessed files breaks.

thanks for this. Best wishes.

**Comment by smile4yourself** [comment] 2022-03-06 22:31
I have something new to share on the above problem. I removed all the mp4 files that I had in my vault and the vault size went from 11Gig to 1 Gig. The plugin then worked. regards

**Comment by gluecode** [comment] 2022-03-09 19:58
My vault is very small (~5 MB) and all text. Checklist does not load and keeps the spinner running forever. I'm on Obsidian 0.13.31 and latest version of Checklist plugin.

![checklist](https://user-images.githubusercontent.com/15410/157523580-23067431-c5e5-4851-98bb-e98bb3b9a196.png)

**Comment by zen010101** [comment] 2022-03-16 04:09
me too . It's too long to load the checklist plugin every time I start the Obsidian.

**Comment by pidgeon777** [comment] 2022-03-16 13:00
I have the same problem, my vault is around 820 KB in size.

**Comment by dwharrison** [comment] 2022-03-31 12:30
I'm now having this problem on my work Windows computer, but not on my personal Mac.  My vault is about 15 MB. The work computer has corporate security software that does slow things down, so that could be involved - mentioning it in case it is a clue.  Note that this problem just started recently.

**Comment by generic-user** [comment] 2022-04-13 09:30
Hi, I had this as well and found what was causing the problem: when you have an empty check somewhere in your scanned files, it seems to block the process. Adding something to that empty line fixed the problem.
Change all occurrences of this:
![image](https://user-images.githubusercontent.com/1516035/163145441-28512cac-74ab-4121-8dc9-dac51a7d4b22.png)
Into this:
![image](https://user-images.githubusercontent.com/1516035/163145714-88732c10-a0f3-4c1c-90bd-0c009a3928a4.png)

As a permanent fix, it would be nice if the processor skips these empty checkboxes.

Hope it helps. 😉

**Comment by pidgeon777** [comment] 2022-04-13 10:41
Nice catch!

Hopefully, now that you identified the cause, the issue will be fixed 👍.

**Comment by rickalex21** [comment] 2022-04-30 22:22
I'm having the same problem. I tried what @generic-user said and deleted the empty check. It was working for a while, then it no longer works. All I see is a spinning circle, which makes the plugin unusable. I'm not sure if I have to delete the cache or do something else? I reinstalled the plugin but that did not help fix the issue.

**Comment by generic-user** [comment] 2022-05-02 07:53
Hi, sometimes this works to force refresh. @rickalex21 
![image](https://user-images.githubusercontent.com/1516035/166202092-16159cfe-4428-4961-8c39-1875d1202be1.png)

**Closed** 2022-07-21 19:34 UTC
Labels: enhancement
