### ISSUE TITLE
Bug: Clicking on wikilink in checklist sidebar is trying to open in external app

### ISSUE THREAD

**Issue by notes-17** [delashum/obsidian-checklist-plugin#56] opened 2021-05-17 07:18 UTC
<img width="313" alt="issue" src="https://user-images.githubusercontent.com/62109484/118446821-ae337d80-b70d-11eb-872e-6b5c5eee46f2.png">

I have wikilinks in my checklist. When I click the wikilink, the page opens but the above mentioned popup appears. If it is a bug please fix it. If not add an option to disable it.

**Comment by delashum** [comment] 2021-05-22 23:01
dupe of #47

**Closed by delashum** 2021-05-22 23:01 UTC
