### ISSUE TITLE
Performance Issue: Keeps Obsidian unresponsive for the first couple of seconds after start

### ISSUE THREAD

**Issue by robbeofficial** [delashum/obsidian-checklist-plugin#97] opened 2021-11-03 09:47 UTC
Thanks for providing this plugin! I really love using it. However, I have to keep it inactive for now due to the following performance issue: 

I'm running obsidian v0.12.19 on windows 10 and checklist v1.2.3. My vault has around 600 items. When the checklist plugin is activated, obsidian remains unresponsive for the first couple of seconds after start (even if checklist is not shown). When the checklist plugin is unactive, this behavior does not occur. I repeaded this test three time to be sure. It looks like the plugin is somehow slowing down the main obsidian thread

This issue is possibly related to #70 .

**Comment by andromedarabbit** [comment] 2021-12-22 04:33
WIth checklist plugin, Obsidian renderer makes CPU usages spike when a large file is added to the vault.

**Comment by delashum** [comment] 2021-12-28 17:16
This is a duplicate of #70 and I will be posting some updates in that issue, so please follow there!

**Closed by delashum** 2021-12-28 17:16 UTC
