### ISSUE TITLE
When I use the mobile version and display it on my iPhone, words with only Chinese characters are displayed vertically. Also, when the file name is only numbers, the back part is omitted.

### ISSUE THREAD

**Issue by rakugakijin** [delashum/obsidian-checklist-plugin#89] opened 2021-09-27 04:32 UTC

**Comment by rakugakijin** [comment] 2021-09-27 22:05
![image](https://user-images.githubusercontent.com/65814903/134991537-3f591540-d512-4f11-8b0e-03e7c4f1207d.jpeg)
It is a frame of eight characters from the right edge, and if there is a Japanese character, it will be displayed vertically.

**Comment by delashum** [comment] 2022-01-09 02:55
duplicate of #78

**Closed by delashum** 2022-01-09 02:55 UTC
