### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by torstenkoepke** [delashum/obsidian-checklist-plugin#11] opened 2021-01-31 12:28 UTC
I get the attached error 
![Bild 31 01 21 um 13 25](https://user-images.githubusercontent.com/49446717/106383749-ef568a80-63c7-11eb-8b19-9fa4a7a05942.jpg)

**Comment by delashum** [comment] 2021-01-31 16:02
From what i understand, this error is normal and shouldn't affect the download of updates. did the download still work?

**Comment by torstenkoepke** [comment] 2021-01-31 17:16
My real problem is that the tasks are shown completely directly after installing, after reopening Obsidian they are often  reduced to just 5 out of four files instead 30 out of 10 files or even to none at all. I thought the debugger console would give me a hint what's going on.

I thought this error message is related to the issue. One way to get my tasks back is deleting the plugin, restarting Obsidian and reinstalling.  ⌘-R did not do the trick.

But the other way is to edit one file with tasks, this seem to trigger a reload and then the tasks seem to 'come back'. I trust you know where to look for the bug--

**Comment by delashum** [comment] 2021-01-31 17:33
Yeah I have an idea where to look. The issue is sometimes the file cache isn't fully loaded by the time the view is loaded, so not all files are indexed. I have an idea of how to resolve this

**Comment by delashum** [comment] 2021-02-03 00:02
This was resolved with #10

**Closed by delashum** 2021-02-03 00:02 UTC
